'''
COLOCALIZATIONS

AUTHOR      : CHAO DAI
LAST UPDATE : 2023-01-16

This smk file houses miscellaneous rules that produce files that are not part of
main pipeline



'''





#----------------------------------------------------------------------------
# 
#----------------------------------------------------------------------------





# def getMakeBigwigParams(wildcards):
#     if wildcards.dataset == 'mRNA':
#         return ''
#     elif wildcards.dataset == 'chRNA':
#         return ''
#     else: 
#         sys.stderr.write("Incorrect dataset! mRNA or chRNA only.\n")
#         exit(1)

# rule makeBigwig:
#     '''
#     Only for mRNA dataset.
#     chRNA bigwig was generated by BF.
#     '''
#     input: 'results/{dataset}/{population}/mergedBams/{indID}_merged.bam'
#     output: 'results/{dataset}/{population}/bigwig/{indID}.bw'
#     params:
#         getMakeBigwigParams
#     threads: 2
#     resources: cpu=2, mem_mb=15000, time=2000
#     shell:
#         '''
#         bamCoverage -b {input} -o {output} -of bigwig \
#             --binSize 1 \
#             -p {threads} \
#             --effectiveGenomeSize 2913022398 \
#             --normalizeUsing RPKM
#         '''


rule mergedBamFlagstat:
    '''
    Get flagstat of merged bam files. Used to get library size
    '''
    input: 'results/{dataset}/{population}/mergedBams/{indID}_merged.bam'
    output: 'results/{dataset}/{population}/mergedBams/{indID}.flagstat.txt'
    threads: 1
    shell:
        '''
        samtools flagstat -@ {threads} -O tsv {input} > {output}
        '''





































































